packages:
  - "*"

allowBuilds:
  "@google/genai": false
  esbuild: set this to true or false
  lefthook: set this to true or false
  msgpackr-extract: set this to true or false
  protobufjs: false
  workerd: set this to true or false
