import assert from "node:assert/strict";
import { SessionManager } from "@earendil-works/pi-coding-agent";
import { CHECKPOINT_TYPE, RESET_TYPE, createCheckpoint, latestCheckpoint, projectCheckpoint, revisionText } from "./projection.ts";

const manager = SessionManager.inMemory();
manager.appendMessage({ role: "system", content: "SYSTEM_OUTSIDE_MIRROR", timestamp: 0 });
manager.appendMessage({ role: "user", content: "Old request", timestamp: 1 });
const raw = manager.buildSessionProjection();
const newEntry = structuredClone(raw.entries.at(-1)!);
newEntry.sourceEntry.id = "new-note";
newEntry.messages = [{ role: "user", content: "Inserted note", timestamp: 0 }];
const edited = { ...raw, entries: [raw.entries[0]!, newEntry], messages: [...raw.entries[0]!.messages, ...newEntry.messages] };
const checkpoint = createCheckpoint(raw, edited, raw);
manager.appendCustomEntry(CHECKPOINT_TYPE, checkpoint);
manager.appendMessage({ role: "user", content: "Fresh suffix", timestamp: 2 });
const projectedRaw = manager.buildSessionProjection();
const active = projectCheckpoint(projectedRaw, latestCheckpoint(manager.getBranch(), projectedRaw));
assert.deepEqual(active.messages.map((message) => message.role), ["system", "user", "user"]);
assert.match(JSON.stringify(active.messages), /Inserted note/);
assert.match(JSON.stringify(active.messages), /Fresh suffix/);
assert.doesNotMatch(JSON.stringify(active.messages), /Old request/);
assert.match(revisionText(manager.getBranch()), /Inserted note/);
assert.doesNotMatch(revisionText(manager.getBranch()), /SYSTEM_OUTSIDE_MIRROR/);
manager.appendCustomEntry(RESET_TYPE, {});
assert.equal(latestCheckpoint(manager.getBranch(), manager.buildSessionProjection()), undefined);
const stale = structuredClone(projectedRaw);
stale.entries[1]!.messages = [{ role: "user", content: "changed prefix", timestamp: 1 }];
assert.throws(() => projectCheckpoint(stale, checkpoint), /stale/);
console.log("live projection selftest passed");
